server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fitnessdb
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
