server:
  port: 8080
spring:
  security:
    user:
      name: Anar
      password: 1234
  datasource:
    url: jdbc:postgresql://localhost:5432/fitnessdb
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  secret: QXZHZ0h3NXZsZlFqNFg2V2FQa2FXaGlJRXNRa2wzSExxTEZ2TjY1RQ==
  expiration: 86400000
